/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDiscountsRouteImport } from './routes/_authenticated/discounts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedBreakageHistoryRouteImport } from './routes/_authenticated/breakage-history'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicHooksDailyReportRouteImport } from './routes/api/public/hooks/daily-report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscountsRoute = AuthenticatedDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreakageHistoryRoute =
  AuthenticatedBreakageHistoryRouteImport.update({
    id: '/breakage-history',
    path: '/breakage-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksDailyReportRoute =
  ApiPublicHooksDailyReportRouteImport.update({
    id: '/api/public/hooks/daily-report',
    path: '/api/public/hooks/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/breakage-history': typeof AuthenticatedBreakageHistoryRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discounts': typeof AuthenticatedDiscountsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/breakage-history': typeof AuthenticatedBreakageHistoryRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discounts': typeof AuthenticatedDiscountsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/breakage-history': typeof AuthenticatedBreakageHistoryRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discounts': typeof AuthenticatedDiscountsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit-log'
    | '/breakage-history'
    | '/categories'
    | '/checkout'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/profile'
    | '/security'
    | '/settings'
    | '/staff'
    | '/transfers'
    | '/warehouses'
    | '/api/public/hooks/daily-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit-log'
    | '/breakage-history'
    | '/categories'
    | '/checkout'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/profile'
    | '/security'
    | '/settings'
    | '/staff'
    | '/transfers'
    | '/warehouses'
    | '/api/public/hooks/daily-report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/audit-log'
    | '/_authenticated/breakage-history'
    | '/_authenticated/categories'
    | '/_authenticated/checkout'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/discounts'
    | '/_authenticated/inventory'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/transfers'
    | '/_authenticated/warehouses'
    | '/api/public/hooks/daily-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksDailyReportRoute: typeof ApiPublicHooksDailyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discounts': {
      id: '/_authenticated/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AuthenticatedDiscountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breakage-history': {
      id: '/_authenticated/breakage-history'
      path: '/breakage-history'
      fullPath: '/breakage-history'
      preLoaderRoute: typeof AuthenticatedBreakageHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/daily-report': {
      id: '/api/public/hooks/daily-report'
      path: '/api/public/hooks/daily-report'
      fullPath: '/api/public/hooks/daily-report'
      preLoaderRoute: typeof ApiPublicHooksDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBreakageHistoryRoute: typeof AuthenticatedBreakageHistoryRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscountsRoute: typeof AuthenticatedDiscountsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBreakageHistoryRoute: AuthenticatedBreakageHistoryRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscountsRoute: AuthenticatedDiscountsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksDailyReportRoute: ApiPublicHooksDailyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
